### ISSUE TITLE
add support for omx

### ISSUE THREAD

**Issue by bstabler** [RSGInc/rJourney#6]
See https://github.com/jpn--/omx-freepascal and https://github.com/osPlanning/omx/wiki/Specification

**Comment by bstabler** [comment]
We need to read and write OMX in addition to txt.  Given this [model config file](https://github.com/RSGInc/rJourney/blob/beijing/BTI_LDConfig_test1.txt), we need to update it as follows:

Before

```
RoadLOSFileName             inputs\zoneAutoLOS_1.txt
RailLOSFileName             inputs\zoneRailLOS_1.txt
BusLOSFileName              inputs\zoneBusLOS_1.txt
AutoVehicleTripMatrixFileName  outputs\auto_vtrip_test1.csv
AutoPersonTripMatrixFileName   outputs\auto_ptrip_test1.csv
BusPersonTripMatrixFileName    outputs\bus_ptrip_test1.csv
RailPersonTripMatrixFileName   outputs\rail_ptrip_test1.csv
```

After

```
RoadLOSFileName             inputs\zoneAutoLOS_1.omx
RailLOSFileName             inputs\zoneRailLOS_1.omx
BusLOSFileName              inputs\zoneBusLOS_1.omx
AutoVehicleTripMatrixFileName  outputs\auto_vtrip_test1.omx
AutoPersonTripMatrixFileName   outputs\auto_ptrip_test1.omx
BusPersonTripMatrixFileName    outputs\bus_ptrip_test1.omx
RailPersonTripMatrixFileName   outputs\rail_ptrip_test1.omx
```

Maybe add a new parameter `OMXFormat         T` or just assume OMX format if file extension is omx.  

If the zone system of the files are the same (i.e. there are 2000 road zones, 2000 rail zones, 2000 bus zones, then the matrices can all be in one OMX file).

**Comment by mabcal** [comment]
The new version will not write out matrices, just a tour list.  So, we don’t need the OMX write capability, just the ability to read a matrix, one row at a time.

Mark

**Comment by bstabler** [comment]
ok
